services:
  web:
    build: .
    ports:
      - "5000:80"  # Exposes port 80 from the container on port 5000 on your host
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - postgres 
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=AppDB
    ports:
      - "5432:5432"
